#!/usr/bin/env python3

import argparse
import asyncio
import io
import os
import shutil
import signal
import socket
import struct
import subprocess
import sys
from pathlib import Path

from aiohttp import web

PROJECT_ROOT = Path(__file__).resolve().parent.parent
UTILS_DIR = PROJECT_ROOT / "utils"
sys.path.insert(0, str(UTILS_DIR))

from persistent_stores import eeprom
from simulator.printer import MachineType
from simulator.simulator import Simulator


EEPROM_DEFAULTS = {
    "Run Selftest": struct.pack("<B", False),
    "Run XYZ Calibration": struct.pack("<B", False),
    "Run First Layer": struct.pack("<B", False),
    "FSensor Enabled": struct.pack("<B", False),
    "Selftest Result Gears": 21 * b"\xaa",
}

DEMO_GCODE = """; UI_DEMO.gcode
; Emulator-only UI test file.
; generated by Codex for MK4/MK4S menu testing
G90 ; absolute positioning
G21 ; millimeters
G28 ; home axes
G1 Z5 F900
G1 X40 Y40 F6000
G1 X180 Y40 F6000
G1 X180 Y180 F6000
G1 X40 Y180 F6000
G1 X40 Y40 F6000
G1 Z10 F900
M84 ; disable motors
"""


def port_available(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            probe.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


def available_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


CONTROL_PANEL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prusa MK4 Emulator</title>
<style>
:root { color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
* { box-sizing: border-box; }
body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: #111315; color: #f4f4f4; }
main { width: min(100% - 32px, 760px); padding: 28px; border: 1px solid #34373b; border-radius: 24px; background: #1b1e21; box-shadow: 0 24px 80px #0008; }
header { display: flex; justify-content: space-between; align-items: baseline; gap: 16px; margin-bottom: 20px; }
h1 { margin: 0; font-size: 22px; letter-spacing: -.02em; }
#status { color: #9ea3a8; font-size: 13px; }
.display { width: min(100%, 640px); margin: auto; padding: 18px; border-radius: 18px; background: #090a0b; border: 1px solid #3a3d41; }
#screen { display: block; width: 100%; aspect-ratio: 3 / 2; object-fit: contain; image-rendering: pixelated; background: #000; }
.controls { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 20px auto 0; width: min(100%, 640px); }
button { min-height: 58px; border: 1px solid #44484d; border-radius: 14px; background: #292d31; color: white; font: inherit; font-weight: 650; cursor: pointer; }
button:hover { background: #34383d; border-color: #666b71; }
button:active { transform: translateY(1px); background: #f15a24; border-color: #f15a24; }
kbd { padding: 2px 6px; border: 1px solid #555a60; border-radius: 5px; background: #202327; color: #c8cbd0; font-size: 11px; }
.hint { margin: 16px 0 0; text-align: center; color: #969ba1; font-size: 13px; }
</style>
</head>
<body>
<main>
  <header><h1>Prusa MK4 Emulator</h1><span id="status">Connecting…</span></header>
  <div class="display"><img id="screen" alt="Emulated MK4 display"></div>
  <div class="controls">
    <button data-action="up">Rotate up<br><kbd>W</kbd></button>
    <button data-action="press">Press knob<br><kbd>Enter</kbd></button>
    <button data-action="down">Rotate down<br><kbd>S</kbd></button>
  </div>
  <p class="hint">The framebuffer refreshes automatically. Keep this terminal open while testing.</p>
</main>
<script>
const image = document.querySelector('#screen');
const status = document.querySelector('#status');
let refreshing = false;
async function refresh() {
  if (refreshing) return;
  refreshing = true;
  const next = new Image();
  next.onload = () => { image.src = next.src; status.textContent = 'Live'; refreshing = false; };
  next.onerror = () => { status.textContent = 'Waiting for firmware…'; refreshing = false; };
  next.src = '/screen.png?t=' + Date.now();
}
async function control(action) {
  status.textContent = 'Sending input…';
  await fetch('/api/' + action, { method: 'POST' });
  setTimeout(refresh, 30);
}
document.querySelectorAll('button').forEach(button => button.addEventListener('click', () => control(button.dataset.action)));
document.addEventListener('keydown', event => {
  if (event.repeat) return;
  const action = event.key.toLowerCase() === 'w' ? 'up' : event.key.toLowerCase() === 's' ? 'down' : event.key === 'Enter' || event.key === ' ' ? 'press' : null;
  if (action) { event.preventDefault(); control(action); }
});
refresh();
setInterval(refresh, 150);
</script>
</body>
</html>
"""


def create_sparse_file(path: Path, size: int) -> None:
    with path.open("wb") as file:
        file.seek(size - 1)
        file.write(b"\0")


def prepare_state(
    state_dir: Path, firmware_bbf: Path
) -> tuple[Path, Path, Path, Path, Path]:
    state_dir.mkdir(parents=True, exist_ok=True)
    tmp_dir = state_dir / "tmp"
    usb_dir = state_dir / "usbdir"
    tmp_dir.mkdir(exist_ok=True)
    usb_dir.mkdir(exist_ok=True)

    xflash = state_dir / "xflash.bin"
    eeprom_bank_1 = state_dir / "eeprom-bank-1.bin"
    eeprom_bank_2 = state_dir / "eeprom-bank-2.bin"

    if not xflash.exists():
        create_sparse_file(xflash, 2**23)

    if not eeprom_bank_1.exists():
        bank_data = eeprom.generate_bank(
            sequence_id=1,
            version=1,
            items=[(name, bytes(value)) for name, value in EEPROM_DEFAULTS.items()],
        )
        eeprom_bank_1.write_bytes(bank_data)

    if not eeprom_bank_2.exists():
        create_sparse_file(eeprom_bank_2, 8192)

    shutil.copy2(firmware_bbf, usb_dir / "firmware.bbf")
    demo_gcode = usb_dir / "UI_DEMO.gcode"
    if not demo_gcode.exists():
        demo_gcode.write_text(DEMO_GCODE, encoding="utf-8")
    return tmp_dir, usb_dir, xflash, eeprom_bank_1, eeprom_bank_2


async def run(args: argparse.Namespace) -> None:
    build_dir = args.build_dir.resolve()
    state_dir = args.state_dir.resolve()
    simulator_path = args.simulator_path.resolve()
    firmware_elf = build_dir / "firmware"
    firmware_bbf = build_dir / "firmware.bbf"
    pid_file = state_dir / "emulator.pid"

    for required in (simulator_path, firmware_elf, firmware_bbf):
        if not required.exists():
            raise FileNotFoundError(required)

    if not port_available(args.web_port):
        if not pid_file.exists():
            raise RuntimeError(
                f"Web port {args.web_port} is already in use; choose another with "
                "MK4_EMULATOR_WEB_PORT"
            )

        try:
            previous_pid = int(pid_file.read_text().strip())
            os.kill(previous_pid, signal.SIGINT)
        except (OSError, ValueError):
            raise RuntimeError(
                f"Web port {args.web_port} is occupied and the previous emulator "
                "could not be stopped"
            ) from None

        print(f"Restarting the existing emulator process {previous_pid}...", flush=True)
        for _ in range(50):
            if port_available(args.web_port):
                break
            await asyncio.sleep(0.1)
        else:
            raise RuntimeError("Previous emulator did not release its web port")

    tmp_dir, usb_dir, xflash, eeprom_bank_1, eeprom_bank_2 = prepare_state(
        state_dir, firmware_bbf
    )

    print("MK4 emulator storage attached:", flush=True)
    print(f"  External flash: {xflash}", flush=True)
    print(f"  EEPROM bank 1: {eeprom_bank_1}", flush=True)
    print(f"  EEPROM bank 2: {eeprom_bank_2}", flush=True)
    print(f"  USB drive:     {usb_dir}", flush=True)
    print("The first start may show 'Installing' for roughly 15–30 seconds.", flush=True)

    scriptio_port = available_port()

    pid_file.write_text(str(os.getpid()))
    try:
        async with Simulator.run(
            simulator_path=simulator_path,
            machine=MachineType.MK4,
            firmware_path=firmware_elf,
            tmpdir=tmp_dir,
            mount_dir_as_flash=usb_dir,
            eeprom_content=(eeprom_bank_1, eeprom_bank_2),
            xflash_content=xflash,
            scriptio_port=scriptio_port,
            nographic=True,
            usbserial=False,
        ) as simulator:
            command_lock = asyncio.Lock()

            async def screen_handler(_request: web.Request) -> web.Response:
                async with command_lock:
                    image = await simulator.screen_take_screenshot()
                    output = io.BytesIO()
                    image.save(output, format="PNG")
                return web.Response(
                    body=output.getvalue(),
                    content_type="image/png",
                    headers={"Cache-Control": "no-store"},
                )

            async def control_handler(request: web.Request) -> web.Response:
                action = request.match_info["action"]
                async with command_lock:
                    if action == "up":
                        await simulator.encoder_rotate_left()
                    elif action == "down":
                        await simulator.encoder_rotate_right()
                    elif action == "press":
                        await simulator.encoder_click()
                    else:
                        raise web.HTTPNotFound()
                return web.json_response({"ok": True})

            async def index_handler(_request: web.Request) -> web.Response:
                return web.Response(text=CONTROL_PANEL, content_type="text/html")

            app = web.Application()
            app.router.add_get("/", index_handler)
            app.router.add_get("/screen.png", screen_handler)
            app.router.add_post("/api/{action}", control_handler)
            runner = web.AppRunner(app)
            await runner.setup()
            site = web.TCPSite(runner, "127.0.0.1", args.web_port)
            await site.start()

            web_url = f"http://127.0.0.1:{args.web_port}"
            print(f"Browser control panel: {web_url}", flush=True)
            print("Controls: W/S rotate the knob, Enter presses it.", flush=True)
            subprocess.run(["open", web_url], check=False)
            try:
                return_code = await simulator.process.wait()
                if return_code:
                    raise RuntimeError(f"Mini404 exited with status {return_code}")
            finally:
                await runner.cleanup()
    finally:
        try:
            if pid_file.read_text().strip() == str(os.getpid()):
                pid_file.unlink()
        except FileNotFoundError:
            pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the MK4 firmware in Mini404")
    parser.add_argument("--build-dir", required=True, type=Path)
    parser.add_argument("--simulator-path", required=True, type=Path)
    parser.add_argument("--state-dir", required=True, type=Path)
    parser.add_argument("--web-port", default=8042, type=int)
    return parser.parse_args()


if __name__ == "__main__":
    try:
        asyncio.run(run(parse_args()))
    except KeyboardInterrupt:
        pass
    except Exception as error:
        print(f"MK4 emulator failed: {error}", file=sys.stderr)
        raise SystemExit(1)
